# Generated by Django 5.1.3 on 2024-11-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('article_number', models.CharField(max_length=100)),
                ('date_end', models.DateField()),
                ('name_pump', models.CharField(max_length=100)),
                ('wc_number', models.CharField(max_length=100)),
                ('name_partner', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
            ],
        ),
    ]
